version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_PORT: 3318

    steps:
      - checkout
      - run: npm install
      - run: npm run tsc
      - run: npm test
